spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iamankitkuswaha/config-server.git
          clone-on-start: true

server:
  port: 8085




